import type {
  StoryRequest,
  StoryResponse,
  Story,
  CreateStoryRequest,
} from "../types";

const BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8080";

export async function generateStory(
  request: StoryRequest,
  authenticatedFetch: (url: string, options?: RequestInit) => Promise<Response>
): Promise<StoryResponse> {
  console.log("Sending story generation request:", request);

  // Convert StoryRequest to CreateStoryRequest format
  const createRequest: CreateStoryRequest = {
    hero: request.character,
    theme: request.theme.join(", "), // Convert array to string
    tone: "Friendly", // Default tone
    twist: request.twist || "NONE", // Default twist
    content: "", // Will be generated by backend
    coverImageUrl: undefined,
  };

  const response = await authenticatedFetch(`${BASE_URL}/api/stories`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(createRequest),
  });

  console.log("Story generation response status:", response.status);

  if (!response.ok) {
    const message = await safeReadText(response);
    console.error("Story generation failed:", response.status, message);
    throw new Error(message || `Request failed with status ${response.status}`);
  }

  const savedStory = (await response.json()) as Story;
  console.log("Story generation and save successful:", savedStory);

  // Convert back to StoryResponse format for compatibility
  return {
    story: savedStory.content,
    savedStoryId: savedStory.id, // Include the saved story ID
  };
}

async function safeReadText(response: Response): Promise<string | undefined> {
  try {
    return await response.text();
  } catch {
    return undefined;
  }
}
