services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: entertainmentdb
      POSTGRES_PASSWORD: entertainmentdb
      POSTGRES_DB: entertainmentdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
