server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_JWT_ISSUER_URI:}
  datasource:
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
    hikari:
      maxLifetime: 300000
      validationTimeout: 3000
      connectionTimeout: 30000
      idleTimeout: 600000

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:}
    show-sql: ${JPA_SHOW_SQL:}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Application specific configuration
app:
  base:
    url: ${APP_BASE_URL:http://localhost:8080}

# External API configurations
GEMINI_API_KEY: ${GEMINI_API_KEY:}
CONVERT_API_TOKEN: ${CONVERT_API_TOKEN:}

# Logging configuration
logging:
  level:
    com.bestgroup.HomeEntertAInment: ${LOG_LEVEL:INFO}
    org.springframework.web: ${SPRING_WEB_LOG_LEVEL:INFO}
