spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/entertainmentdb}
    username: ${JDBC_DATABASE_USERNAME:entertainmentdb}
    password: ${JDBC_DATABASE_PASSWORD:entertainmentdb}
    hikari:
      maxLifetime: 300000
      validationTimeout: 3000
      connectionTimeout: 30000
      idleTimeout: 600000

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  base:
    url: ${APP_BASE_URL:http://localhost:8080}

GEMINI_API_KEY: ${GEMINI_API_KEY}

# ConvertAPI configuration for PDF to text conversion
CONVERT_API_TOKEN: ${CONVERT_API_TOKEN}
